---
- hosts: all
  become: yes
  tasks:
    - name: Detect the distribution
      command: cat /etc/os-release
      register: os_release

    - name: Install Docker on Debian/Ubuntu
      when: "'ID=ubuntu' in os_release.stdout or 'ID=debian' in os_release.stdout"
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Install Docker on Amazon Linux
      when: "'ID=\"amzn\"' in os_release.stdout"
      yum:
        name: docker
        state: present

    - name: Install Docker on CentOS/RHEL
      when: "'ID=centos' in os_release.stdout or 'ID=rhel' in os_release.stdout"
      yum:
        name: docker
        state: present

    - name: Start Docker service on all distributions
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create user serveurweb
      user:
        name: serveurweb
        state: present
        create_home: yes
        shell: /bin/bash
        password: "$1$HHC8wiE7$XQdY5e3wpwLjgRfgbusVc0" # Remplacez par votre mot de passe chiffré

    - name: Add user serveurweb to docker group
      user:
        name: serveurweb
        groups: docker
        append: yes

