version: '3.8'

services:
  db:
    image: mariadb:lts
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_interval: '5s'
      timeout: '5s'
      retries: 5


  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://flaskuser:flaskpassword@db/flaskdb

volumes:
  db_data: